version: 2.1
jobs:
   build:
     working_directory: /stackwalk
     docker:
       - image: hhyyrylainen/stackwalk-deps:v1
     steps:
       - checkout
       - restore_cache:
           keys:
             - v1-deps-{{ arch }}-{{ checksum "setup.rb" }}-{{ checksum "stack_walk_dependencies.rb" }}
             - v1-deps-{{ arch }}
       - restore_cache:
           keys:
             - v1-build-{{ arch }}-{{ .Branch }}
       - run: ./Setup.rb --no-packagemanager --no-updates -j 5
       - save_cache:
           key: v1-deps-{{ arch }}-{{ checksum "setup.rb" }}-{{ checksum "stack_walk_dependencies.rb" }}
           paths:
             - ThirdParty
       - save_cache:
           key: v1-deps-{{ arch }}
           paths:
             - ThirdParty
       - save_cache:
           key: v1-build-{{ arch }}-{{ .Branch }}
           paths:
             - build/src
             - build/test
             - build/CMakeFiles
             - build/CMakeCache.txt
             - build/Makefile
       # - run:
       #     command: ./test "~[xrequired]"
       #     working_directory: ~/stackwalk/build/test
